name: Publish Docker image
on:
  release:
    types: [published]
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'


jobs:
  build_and_push:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      # Action can be useful if you want to add emulation support with QEMU to
      # be able to build against more platforms
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # This is not required but recommended using it to be able to build
      # multi-platform images, export cache, etc
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # Set up metadata and tags automatically
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: dylanratcliffe/deviant-ingest
          # https://github.com/marketplace/actions/docker-meta#semver
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: build/package/Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

