name: Remove old package versions
on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:
jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - name: purge packages
        uses: MobileheadHolding/github-action-purge-packages@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
