---  
name: Go
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    services:
      dgraph:
        image: dgraph/standalone:latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test
      run: go test -v ./...
      env:
        REDACTED_DGRAPH_HOST: dgraph
