---  
name: Acceptance Tests & Package
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    services:
      dgraph:
        image: dgraph/standalone:latest
        ports:
          - 9080:9080
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test
      run: go test -v ./...
  push:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      # Action can be useful if you want to add emulation support with QEMU to
      # be able to build against more platforms
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # This is not required but recommended using it to be able to build
      # multi-platform images, export cache, etc
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # Set up metadata and tags automatically
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/dylanratcliffe/deviant-ingest
          # https://github.com/marketplace/actions/docker-meta#semver
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: build/package/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

